### PR TITLE
Language: pt-BR

### PR DESCRIPTION
**Pull request by brunominervino**

### CODE REVIEW

**Comment by Super-Baleine** [comment]
Hi,
The translations project migrated to [crowdin](https://crowdin.com/project/protonmail) a while ago :)

**Comment by brunominervino** [comment]
@Super-Baleine 
Thank you! Who I can talk to create a new translation to Brazilian Portuguese?

**Comment by Super-Baleine** [comment]
You're welcome :)

capture d ecran de 2017-08-28 22-00-12

Click on "contact" below "PMTranslator" x)

**Comment by brunominervino** [comment]
Thanks! I will close this pr.

**Pull request closed without merging**
