### PR TITLE
Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by devreis**
Brazilian Portuguese translation

### CODE REVIEW

**Comment by devreis** [comment]
Fixed some capital letters

**Comment by N3tt3rm4n** [comment]
:point_up: There already is a translation in PR #13...
<sup>[But I do not speak Brazilian Portuguese so I can't tell which one is better]</sup>

**Comment by devreis** [comment]
@N3tt3rm4n The #13 says portuguese, the Portugal Portuguese and Brazil Portuguese are different. And both #13 and #16 are not complete in the last lines...

**Comment by N3tt3rm4n** [comment]
@devreis Ah ok, didn't check them; was just a notice :smiley:

<sup>BTW: "This is a Brazilian portuguese translation" - #13 </sup>

**Comment by devreis** [comment]
@N3tt3rm4n Earlier i've checked and old version of #13  that was not complete... Yes, it's brazilian portuguese, but i've read the comment that says "it can be used to Portugal portuguese too... I'll remove this pr. Greetings from Brazil!

**Pull request closed without merging**
